### ISSUE TITLE
sastre is not able to connect via IPv6 address to vmanage

### ISSUE THREAD

**Issue by ogelpre** [CiscoDevNet/sastre#4]
I am trying to connect to sastre via IP address:

```
(blub) root@ecmp-1:~# export VMANAGE_IP=2a00:1398:c000:1a00::1
(blub) root@ecmp-1:~# sdwan backup --workdir test all
vManage password: 
Traceback (most recent call last):
  File "/root/blub/lib/python3.9/site-packages/requests/models.py", line 382, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/root/blub/lib/python3.9/site-packages/urllib3/util/url.py", line 394, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://2a00:1398:c000:1a00::1:8443/j_security_check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/blub/bin/sdwan", line 33, in <module>
    sys.exit(load_entry_point('cisco-sdwan==1.16.2', 'console_scripts', 'sdwan')())
  File "/root/blub/lib/python3.9/site-packages/cisco_sdwan/cmd.py", line 146, in main
    with Rest(base_url, cli_args.user, cli_args.password, cli_args.tenant, timeout=cli_args.timeout) as api:
  File "/root/blub/lib/python3.9/site-packages/cisco_sdwan/base/rest_api.py", line 27, in __init__
    if not self.login(username, password, tenant_name):
  File "/root/blub/lib/python3.9/site-packages/cisco_sdwan/base/rest_api.py", line 49, in login
    response = session.post(f'{self.base_url}/j_security_check',
  File "/root/blub/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/root/blub/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/root/blub/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/root/blub/lib/python3.9/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/root/blub/lib/python3.9/site-packages/requests/models.py", line 384, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://2a00:1398:c000:1a00::1:8443/j_security_check

```

My second try was an alternative notation, which throws another error:
```
root@ecmp-1:~# export VMANAGE_IP=[2a00:1398:c000:1a00::1]
root@ecmp-1:~# sdwan backup --workdir test all
vManage password: 
Traceback (most recent call last):
  File "/root/blub/lib/python3.9/site-packages/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/root/blub/lib/python3.9/site-packages/requests/adapters.py", line 315, in get_connection
    conn = self.poolmanager.connection_from_url(url)
  File "/root/blub/lib/python3.9/site-packages/urllib3/poolmanager.py", line 297, in connection_from_url
    u = parse_url(url)
  File "/root/blub/lib/python3.9/site-packages/urllib3/util/url.py", line 394, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://2a00:1398:c000:1a00::1:8443/welcome.html?nocache=1634309009720

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/blub/bin/sdwan", line 33, in <module>
    sys.exit(load_entry_point('cisco-sdwan==1.16.2', 'console_scripts', 'sdwan')())
  File "/root/blub/lib/python3.9/site-packages/cisco_sdwan/cmd.py", line 148, in main
    task_output = task.runner(parsed_task_args, api)
  File "/root/blub/lib/python3.9/site-packages/cisco_sdwan/base/rest_api.py", line 37, in __exit__
    self.logout()
  File "/root/blub/lib/python3.9/site-packages/cisco_sdwan/base/rest_api.py", line 90, in logout
    response = self.session.get(f'{self.base_url}/logout', params={'nocache': str(int(time()))})
  File "/root/blub/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/root/blub/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/blub/lib/python3.9/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/root/blub/lib/python3.9/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/root/blub/lib/python3.9/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/root/blub/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/root/blub/lib/python3.9/site-packages/requests/adapters.py", line 414, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Failed to parse: https://2a00:1398:c000:1a00::1:8443/welcome.html?nocache=1634309009720
```

**Comment by reismarcelo** [comment]
Thank you for reporting this. I'll take a look on it shortly.

**Comment by reismarcelo** [comment]
Hi @ogelpre which version of the requests library are you using? Can you try with a newer version (2.24.0 or newer)? Also, please keep the square brackets when you set VMANAGE_IP.

**Comment by ogelpre** [comment]
@reismarcelo pip automatically installed a newer version:

```
(blub) root@ecmp-1:~# pip3 show requests
Name: requests
Version: 2.26.0
Summary: Python HTTP for Humans.
Home-page: https://requests.readthedocs.io
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /root/blub/lib/python3.9/site-packages
Requires: certifi, charset-normalizer, idna, urllib3
Required-by: cisco-sdwan
```

**Comment by ogelpre** [comment]
@reismarcelo I had a deeper look on it. It is a bug on vmanage and not in sastre.

My test was the following:
```
root@ecmp-1:~# curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "j_username=${VMANAGE_USER}&j_password=${VMANAGE_PASSWORD}" -k -b cookiefile -c cookiefile "https://${VMANAGE_IP}:8443/j_security_check"
root@ecmp-1:~# curl -L -k -b cookiefile -c cookiefile "https://${VMANAGE_IP}:8443/logout"
*   Trying 2a00:1398:c000:1a00::1:8443...
* Connected to 2a00:1398:c000:1a00::1 (2a00:1398:c000:1a00::1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=DE; ST=Baden-Wuerttemberg; L=Karlsruhe; O=Karlsruhe Institute of Technology; OU=SCC-NET; CN=vmanage-1.lab.tmn.scc.kit.edu
*  start date: Aug  4 09:16:06 2021 GMT
*  expire date: Sep  4 09:16:06 2022 GMT
*  issuer: C=DE; ST=Baden-Wuerttemberg; L=Karlsruhe; O=Karlsruhe Institute of Technology; CN=KIT-CA
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /logout HTTP/1.1
> Host: [2a00:1398:c000:1a00::1]:8443
> User-Agent: curl/7.74.0
> Accept: */*
> Cookie: JSESSIONID=FAcbN-hyt5zf8eTiPw6sJ7ofP7mpmZEl2gpbt2gj.c75fbd1e-5fa9-4215-8445-b36a89e7cdfa
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< expires: Fri Oct 22 23:05:52 CEST 2021
< cache-control: no-cache, no-store
* Replaced cookie JSESSIONID="FAcbN-hyt5zf8eTiPw6sJ7ofP7mpmZEl2gpbt2gj-invalid" for domain 2a00:1398:c000:1a00::1, path /, expire 0
< set-cookie: JSESSIONID=FAcbN-hyt5zf8eTiPw6sJ7ofP7mpmZEl2gpbt2gj-invalid
< x-xss-protection: 1; mode=block
< pragma: no-cache
< x-frame-options: DENY
< location: https://2a00:1398:c000:1a00::1:8443/welcome.html?nocache=1634936752191
< date: Fri, 22 Oct 2021 21:05:52 GMT
< vary: Accept-Encoding
< strict-transport-security: max-age=31536000; includeSubDomains
< x-content-type-options: nosniff
< content-length: 0
< server: svcproxy
< 
* Connection #0 to host 2a00:1398:c000:1a00::1 left intact
curl: (3) URL using bad/illegal format or missing URL
```

Vmanage returns a bad formatted URL in the location header. I will open a bug via TAC.
