### ISSUE TITLE
sdwan command is crashing

### ISSUE THREAD

**Issue by thepkumar28** [CiscoDevNet/sastre#9]
I have been using sastre and sastre-pro tools in my Python virtual environment and it was working as expected, but now both sastre and sastre-pro are not working and it's crashing.
I tried to install sastre and sastre-pro on my new Python virtual environment and after the installation I am unable to execute any commands and getting below error :

(sdwan) [1211656@azlawxasp00001 sdwan]$ sdwan --version
Traceback (most recent call last):
  File "/home/1211656/virtualenvironment/sdwan/bin/sdwan", line 5, in <module>
    from cisco_sdwan.__main__ import main
  File "/home/1211656/virtualenvironment/sdwan/lib64/python3.9/site-packages/cisco_sdwan/__main__.py", line 22, in <module>
    from .tasks.implementation import *
  File "/home/1211656/virtualenvironment/sdwan/lib64/python3.9/site-packages/cisco_sdwan/tasks/implementation/__init__.py", line 11, in <module>
    from ._attach_detach import TaskAttach, TaskDetach, AttachVsmartArgs, AttachEdgeArgs, DetachVsmartArgs, DetachEdgeArgs
  File "/home/1211656/virtualenvironment/sdwan/lib64/python3.9/site-packages/cisco_sdwan/tasks/implementation/_attach_detach.py", line 337, in <module>
    class AttachVsmartArgs(AttachDetachArgs):
  File "/home/1211656/virtualenvironment/sdwan/lib64/python3.9/site-packages/cisco_sdwan/tasks/implementation/_attach_detach.py", line 340, in AttachVsmartArgs
    template_filter: Callable = const(DeviceTemplateIndex.is_vsmart)
  File "/home/1211656/virtualenvironment/sdwan/lib64/python3.9/site-packages/cisco_sdwan/tasks/models.py", line 49, in const
    return Field(default_value, const=True)
  File "/home/1211656/virtualenvironment/sdwan/lib64/python3.9/site-packages/pydantic/fields.py", line 723, in Field
    raise PydanticUserError('const is removed, use Literal instead', code='removed-kwargs')
pydantic.errors.PydanticUserError: const is removed, use Literal instead

For further information visit https://errors.pydantic.dev/2.0.3/u/removed-kwargs

 I have observerd that previously sastre-pro was using pydantic-1.10.7 but now it’s using pydantic-2.0.3.

Could you please help me with this.

**Comment by thepkumar28** [comment]
I have investigated further and found the solution.

The root cause of the issue is :

The sastre-pro installation command "pip install --upgrade ./Sastre-Pro" is downloading pydantic-2.0.3 instead of pydantic-1.10.7

Resolution

Install required Python package using the requirement.txt file (which is already present under Sastre-Pro_1.21.2/Sastre-Pro)

"pip install -r requirements.txt"

This step is missing from the README.txt file, please add this step in the file.
